config/routes.rb
Rails.application.routes.draw do
  root to: "memos#index"
  resources :memos, only: [:index, :new, :create, :destroy] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  validates :item, presence: true
  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController

  def index
    @memos = Memo.all.order(id: "DESC")
  end

  def new
    @memo = Memo.new
  end

  def create
    @memo = Memo.create(memo_params)
    
    if @memo.valid?
      @memo.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @memo = Memo.find(params[:id])
    if @memo.destroy
      redirect_to root_path
    end
  end

  private
  def memo_params
    params.require(:memo).permit(:item, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Original</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header-bar">
        <hi class="title">買い物リスト</hi>
        <div class="add">
          <%= link_to "追加する", new_memo_path, class:"add-btn" %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p>買い物リスト</p>
    </footer>
  </body>
</html>

app/views/memos/index.html.erb
<div class="memos">
  <% @memos.each do |memo| %>
    <div class="memo">
      <div class="memo-item"><%= memo.item %></div>
      <div class="memo-text"><%= memo.text %></div>
      
    <%= link_to '削除', memo_path(memo.id) , method: :delete, class: "delete-btn" %>
  
    </div>
    
  <% end %>
  
</div>

app/views/memos/new.html.erb
<div class="form">
    <h2 class="edit-title">商品の情報を入力</h2>
    <%= form_with(model: @memo, local: true) do |form| %>
    <div class="form-input">
      <div class="item-name"><%= form.text_area :item, placeholder: "商品名", style: "border: none", :size=>"25*20" %></div>
      <div class="item-text"><%= form.text_area :text, placeholder: "追加メモ", style: "border: none", :size=>"25*20" %></div>
    </div> 
      <div class="form-submit"><%= form.submit "追加" %></div>
    <% end %>
</div>